### ISSUE TITLE
QUESTION ABOUT AMADEUS PLAY STORE APP

### ISSUE THREAD

**Issue by jeluchu** [Yink/Amadeus#81]
Good evening, I've been looking at the Play Store, and I've seen that the application of "Amadeus" that is in development here,
have been published and it also have a price set. I don't know if it was uploaded by you or not.
If it wasn't you, you should report it, and anyway I'm not entirely sure because it has the same package name.

Here I leave the link of the app in the Play Store: 
https://play.google.com/store/apps/details?id=com.animewallpro.yink.amadeus

Legal links
https://play.google.com/about/ip-impersonation/ip/
https://support.google.com/legal/contact/lr_dmca?product=googleplay

**Comment by Yink** [comment]
Hi Jeluchu, thank you very much for reaching out to me. These are indeed copycats and I've reported them. It would help me a lot if you could do the same so these products are taken off the play store (there is also a second one). I will **never** upload my app to Google Play store, because it infringes MAGES.'s copyright.
